version: "3.7"

services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_db
    ports:
      - "1221:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - "5370:6379"

  app:
    build:
      context: .
    container_name: fastapi_app
    command: sleep infinity
    #command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/fastapi_app
    ports:
      - "9999:8000"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
      - redis